baseURL = 'https://alexchambers.github.io/'
languageCode = 'en-us'
title = 'Alex Chambers'
theme = 'PaperMod'

[params]
  author = 'Alex Chambers'
  description = 'Personal blog'

  [params.assets]
    favicon = "favicon.svg"
    favicon16x16 = "favicon.svg"
    favicon32x32 = "favicon.svg"
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Alex Chambers"
    Content = "Building software. Learning out loud."

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 20

[outputs]
  home = ['HTML', 'RSS', 'JSON']
